//
// btstack_config.h for libusb port
//
// Documentation: https://bluekitchen-gmbh.com/btstack/#how_to/
//

#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

// Port related features
#define HAVE_ASSERT
#define HAVE_BTSTACK_STDIN
#define HAVE_MALLOC
#define HAVE_POSIX_FILE_IO
#define HAVE_POSIX_TIME


#define ENABLE_CLASSIC
#define ENABLE_BLE
#define ENABLE_EHCILL
#define ENABLE_H5
#define ENABLE_LOG_DEBUG
#define ENABLE_LOG_ERROR
#define ENABLE_LOG_INFO
#define ENABLE_SCO_OVER_HCI
#define ENABLE_SCO_OVER_PCM
#define ENABLE_HFP_WIDE_BAND_SPEECH
#define ENABLE_HFP_AT_MESSAGES
#define ENABLE_LE_PERIPHERAL
#define ENBALE_LE_CENTRAL
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_LE_PROACTIVE_AUTHENTICATION
#define ENABLE_GATT_CLIENT_PAIRING
#define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_LE_EXTENDED_ADVERTISING
#define ENABLE_LE_PERIODIC_ADVERTISING
#define ENABLE_LE_SIGNED_WRITE
#define ENABLE_LE_PRIVACY_ADDRESS_RESOLUTION
#define ENABLE_CROSS_TRANSPORT_KEY_DERIVATION
#define ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_L2CAP_ENHANCED_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
#define ENABLE_HCI_SERIALIZED_CONTROLLER_OPERATIONS
#define ENABLE_ATT_DELAYED_RESPONSE
#define ENABLE_BCM_PCM_WBS
#define ENABLE_CC256X_ASSISTED_HFP
#define Enable_RTK_PCM_WBS
#define ENABLE_CC256X_BAUDRATE_CHANGE_FLOWCONTROL_BUG_WORKAROUND
#define ENABLE_CYPRESS_BAUDRATE_CHANGE_FLOWCONTROL_BUG_WORKAROUND
#define ENABLE_LE_LIMIT_ACL_FRAGMENT_BY_MAX_OCTETS
#define ENABLE_TLV_FLASH_EXPLICIT_DELETE_FIELD
#define ENABLE_CONTROLLER_WARM_BOOT
#define ENABLE_SEGGER_RTT
#define ENABLE_EXPLICIT_CONNECTABLE_MODE_CONTROL
#define ENABLE_EXPLICIT_IO_CAPABILITIES_REPLY
#define ENABLE_EXPLICIT_LINK_KEY_REPLY
#define ENABLE_EXPLICIT_BR_EDR_SECURITY_MANAGER
#define ENABLE_CLASSIC_OOB_PAIRING
#define ENABLE_A2DP_EXPLICIT_CONFIG
#define ENABLE_AVDTP_ACCEPTOR_EXPLICIT_START_STREAM_CONFIRMATION


// BTstack configuration. buffers, sizes, ...
#define HCI_ACL_PAYLOAD_SIZE (1691 + 4)
#define HCI_INCOMING_PRE_BUFFER_SIZE 14 // sizeof BNEP header, avoid memcpy

#define NVM_NUM_DEVICE_DB_ENTRIES      16
#define NVM_NUM_LINK_KEYS              16

// Mesh Configuration
#define ENABLE_MESH
#define ENABLE_MESH_ADV_BEARER
#define ENABLE_MESH_GATT_BEARER
#define ENABLE_MESH_PB_ADV
#define ENABLE_MESH_PB_GATT
#define ENABLE_MESH_PROVISIONER
#define ENABLE_MESH_PROXY_SERVER

#define MAX_NR_MESH_SUBNETS            2
#define MAX_NR_MESH_TRANSPORT_KEYS    16
#define MAX_NR_MESH_VIRTUAL_ADDRESSES 16

// allow for one NetKey update
#define MAX_NR_MESH_NETWORK_KEYS      (MAX_NR_MESH_SUBNETS+1)

#endif

